# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/matflasch/projects/pymp-slim/src/pymp_slim.ui'
#
# Created: Thu Jan 13 17:36:36 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_PympSlimView(object):
    def setupUi(self, PympSlimView):
        PympSlimView.setObjectName("PympSlimView")
        PympSlimView.resize(790, 626)
        self.centralwidget = QtGui.QWidget(PympSlimView)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolb_new = QtGui.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/default/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_new.setIcon(icon)
        self.toolb_new.setObjectName("toolb_new")
        self.horizontalLayout_5.addWidget(self.toolb_new)
        self.toolb_open = QtGui.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/default/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_open.setIcon(icon1)
        self.toolb_open.setObjectName("toolb_open")
        self.horizontalLayout_5.addWidget(self.toolb_open)
        self.toolb_save = QtGui.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/default/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_save.setIcon(icon2)
        self.toolb_save.setObjectName("toolb_save")
        self.horizontalLayout_5.addWidget(self.toolb_save)
        self.toolb_layout_left = QtGui.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/default/layout_lm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_layout_left.setIcon(icon3)
        self.toolb_layout_left.setObjectName("toolb_layout_left")
        self.horizontalLayout_5.addWidget(self.toolb_layout_left)
        self.toolb_layout_right = QtGui.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/default/layout_rm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_layout_right.setIcon(icon4)
        self.toolb_layout_right.setObjectName("toolb_layout_right")
        self.horizontalLayout_5.addWidget(self.toolb_layout_right)
        self.toolb_random = QtGui.QToolButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/default/random_f.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_random.setIcon(icon5)
        self.toolb_random.setObjectName("toolb_random")
        self.horizontalLayout_5.addWidget(self.toolb_random)
        self.toolb_repeat = QtGui.QToolButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/default/repeat_f.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_repeat.setIcon(icon6)
        self.toolb_repeat.setObjectName("toolb_repeat")
        self.horizontalLayout_5.addWidget(self.toolb_repeat)
        self.toolb_clear = QtGui.QToolButton(self.centralwidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/default/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_clear.setIcon(icon7)
        self.toolb_clear.setObjectName("toolb_clear")
        self.horizontalLayout_5.addWidget(self.toolb_clear)
        self.toolb_focus = QtGui.QToolButton(self.centralwidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/default/focus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_focus.setIcon(icon8)
        self.toolb_focus.setObjectName("toolb_focus")
        self.horizontalLayout_5.addWidget(self.toolb_focus)
        self.toolb_shuffle = QtGui.QToolButton(self.centralwidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/default/shuffle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_shuffle.setIcon(icon9)
        self.toolb_shuffle.setObjectName("toolb_shuffle")
        self.horizontalLayout_5.addWidget(self.toolb_shuffle)
        self.toolb_settings = QtGui.QToolButton(self.centralwidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/default/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_settings.setIcon(icon10)
        self.toolb_settings.setObjectName("toolb_settings")
        self.horizontalLayout_5.addWidget(self.toolb_settings)
        self.toolb_love_track = QtGui.QToolButton(self.centralwidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/default/love_track.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_love_track.setIcon(icon11)
        self.toolb_love_track.setObjectName("toolb_love_track")
        self.horizontalLayout_5.addWidget(self.toolb_love_track)
        self.toolb_lastfm = QtGui.QToolButton(self.centralwidget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/default/lfm_f.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_lastfm.setIcon(icon12)
        self.toolb_lastfm.setObjectName("toolb_lastfm")
        self.horizontalLayout_5.addWidget(self.toolb_lastfm)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tree_collection = QtGui.QTreeView(self.centralwidget)
        self.tree_collection.setMinimumSize(QtCore.QSize(180, 0))
        self.tree_collection.setObjectName("tree_collection")
        self.horizontalLayout_6.addWidget(self.tree_collection)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_trackinfo = QtGui.QLabel(self.centralwidget)
        self.label_trackinfo.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_trackinfo.setFont(font)
        self.label_trackinfo.setObjectName("label_trackinfo")
        self.verticalLayout_2.addWidget(self.label_trackinfo)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolb_prev = QtGui.QToolButton(self.centralwidget)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/default/playback_prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_prev.setIcon(icon13)
        self.toolb_prev.setObjectName("toolb_prev")
        self.horizontalLayout.addWidget(self.toolb_prev)
        self.toolb_stop = QtGui.QToolButton(self.centralwidget)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/default/playback_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_stop.setIcon(icon14)
        self.toolb_stop.setObjectName("toolb_stop")
        self.horizontalLayout.addWidget(self.toolb_stop)
        self.toolb_play = QtGui.QToolButton(self.centralwidget)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/default/playback_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_play.setIcon(icon15)
        self.toolb_play.setObjectName("toolb_play")
        self.horizontalLayout.addWidget(self.toolb_play)
        self.toolb_next = QtGui.QToolButton(self.centralwidget)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/default/playback_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_next.setIcon(icon16)
        self.toolb_next.setObjectName("toolb_next")
        self.horizontalLayout.addWidget(self.toolb_next)
        self.toolb_mute = QtGui.QToolButton(self.centralwidget)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/default/speaker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_mute.setIcon(icon17)
        self.toolb_mute.setObjectName("toolb_mute")
        self.horizontalLayout.addWidget(self.toolb_mute)
        self.slider_volume = QtGui.QSlider(self.centralwidget)
        self.slider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.slider_volume.setObjectName("slider_volume")
        self.horizontalLayout.addWidget(self.slider_volume)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_time_start = QtGui.QLabel(self.centralwidget)
        self.label_time_start.setObjectName("label_time_start")
        self.horizontalLayout_2.addWidget(self.label_time_start)
        self.slider_time = QtGui.QSlider(self.centralwidget)
        self.slider_time.setOrientation(QtCore.Qt.Horizontal)
        self.slider_time.setObjectName("slider_time")
        self.horizontalLayout_2.addWidget(self.slider_time)
        self.label_time_stop = QtGui.QLabel(self.centralwidget)
        self.label_time_stop.setObjectName("label_time_stop")
        self.horizontalLayout_2.addWidget(self.label_time_stop)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolb_clear_search = QtGui.QToolButton(self.centralwidget)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/default/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolb_clear_search.setIcon(icon18)
        self.toolb_clear_search.setObjectName("toolb_clear_search")
        self.horizontalLayout_3.addWidget(self.toolb_clear_search)
        self.line_search = QtGui.QLineEdit(self.centralwidget)
        self.line_search.setObjectName("line_search")
        self.horizontalLayout_3.addWidget(self.line_search)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.table_playlist = QtGui.QTableView(self.centralwidget)
        self.table_playlist.setObjectName("table_playlist")
        self.verticalLayout.addWidget(self.table_playlist)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.plain_lyric = QtGui.QPlainTextEdit(self.centralwidget)
        self.plain_lyric.setReadOnly(True)
        self.plain_lyric.setObjectName("plain_lyric")
        self.horizontalLayout_6.addWidget(self.plain_lyric)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        PympSlimView.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(PympSlimView)
        self.statusBar.setObjectName("statusBar")
        PympSlimView.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(PympSlimView)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 790, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        PympSlimView.setMenuBar(self.menuBar)
        self.actionAdd_collection = QtGui.QAction(PympSlimView)
        self.actionAdd_collection.setIcon(icon1)
        self.actionAdd_collection.setObjectName("actionAdd_collection")
        self.actionNew_playlist = QtGui.QAction(PympSlimView)
        self.actionNew_playlist.setIcon(icon)
        self.actionNew_playlist.setObjectName("actionNew_playlist")
        self.actionOpen_playlist = QtGui.QAction(PympSlimView)
        self.actionOpen_playlist.setIcon(icon1)
        self.actionOpen_playlist.setObjectName("actionOpen_playlist")
        self.actionSave_playlist = QtGui.QAction(PympSlimView)
        self.actionSave_playlist.setIcon(icon2)
        self.actionSave_playlist.setObjectName("actionSave_playlist")
        self.actionQuit = QtGui.QAction(PympSlimView)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/default/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon19)
        self.actionQuit.setObjectName("actionQuit")
        self.actionShow_collection = QtGui.QAction(PympSlimView)
        self.actionShow_collection.setIcon(icon3)
        self.actionShow_collection.setObjectName("actionShow_collection")
        self.actionShow_lyric = QtGui.QAction(PympSlimView)
        self.actionShow_lyric.setIcon(icon4)
        self.actionShow_lyric.setObjectName("actionShow_lyric")
        self.actionAbout = QtGui.QAction(PympSlimView)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/default/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon20)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionAdd_collection)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew_playlist)
        self.menuFile.addAction(self.actionOpen_playlist)
        self.menuFile.addAction(self.actionSave_playlist)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionShow_collection)
        self.menuView.addAction(self.actionShow_lyric)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PympSlimView)
        QtCore.QObject.connect(self.toolb_clear_search, QtCore.SIGNAL("clicked()"), self.line_search.clear)
        QtCore.QObject.connect(self.toolb_clear, QtCore.SIGNAL("clicked()"), self.table_playlist.reset)
        QtCore.QMetaObject.connectSlotsByName(PympSlimView)

    def retranslateUi(self, PympSlimView):
        PympSlimView.setWindowTitle(QtGui.QApplication.translate("PympSlimView", "pymp", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_new.setToolTip(QtGui.QApplication.translate("PympSlimView", "new playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_new.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_open.setToolTip(QtGui.QApplication.translate("PympSlimView", "open playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_open.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_save.setToolTip(QtGui.QApplication.translate("PympSlimView", "save playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_save.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_layout_left.setToolTip(QtGui.QApplication.translate("PympSlimView", "show collection", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_layout_left.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_layout_right.setToolTip(QtGui.QApplication.translate("PympSlimView", "show lyric", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_layout_right.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_random.setToolTip(QtGui.QApplication.translate("PympSlimView", "random", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_random.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_repeat.setToolTip(QtGui.QApplication.translate("PympSlimView", "repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_repeat.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_clear.setToolTip(QtGui.QApplication.translate("PympSlimView", "clear playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_clear.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_focus.setToolTip(QtGui.QApplication.translate("PympSlimView", "focus current track", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_focus.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_shuffle.setToolTip(QtGui.QApplication.translate("PympSlimView", "shuffle playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_shuffle.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_settings.setToolTip(QtGui.QApplication.translate("PympSlimView", "settings", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_settings.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_love_track.setToolTip(QtGui.QApplication.translate("PympSlimView", "love (last.fm)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_love_track.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_lastfm.setToolTip(QtGui.QApplication.translate("PympSlimView", "last.fm scrobble", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_lastfm.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_trackinfo.setText(QtGui.QApplication.translate("PympSlimView", "Artist - Track - \n"
"Album(year) [trackno]\n"
"Genre", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_prev.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_stop.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_play.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_next.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_mute.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_start.setText(QtGui.QApplication.translate("PympSlimView", "00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_stop.setText(QtGui.QApplication.translate("PympSlimView", "00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_clear_search.setToolTip(QtGui.QApplication.translate("PympSlimView", "clear search", None, QtGui.QApplication.UnicodeUTF8))
        self.toolb_clear_search.setText(QtGui.QApplication.translate("PympSlimView", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.plain_lyric.setPlainText(QtGui.QApplication.translate("PympSlimView", "lyric", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("PympSlimView", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("PympSlimView", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("PympSlimView", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_collection.setText(QtGui.QApplication.translate("PympSlimView", "add collection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_playlist.setText(QtGui.QApplication.translate("PympSlimView", "new playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_playlist.setText(QtGui.QApplication.translate("PympSlimView", "open playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_playlist.setText(QtGui.QApplication.translate("PympSlimView", "save playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("PympSlimView", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_collection.setText(QtGui.QApplication.translate("PympSlimView", "show collection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_lyric.setText(QtGui.QApplication.translate("PympSlimView", "show lyric", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("PympSlimView", "About", None, QtGui.QApplication.UnicodeUTF8))

import default_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PympSlimView = QtGui.QMainWindow()
    ui = Ui_PympSlimView()
    ui.setupUi(PympSlimView)
    PympSlimView.show()
    sys.exit(app.exec_())

